### ISSUE TITLE
missing ria.util

### ISSUE THREAD

**Issue by maybefreedom** [motatoes/MAdetection#1]

**Comment by maybefreedom** [comment]
Hi! Can you post the code for ria.util.mask2cell and ria.util.cell2mask?

**Comment by maybefreedom** [comment]
Hi! great project! I've been following your code but I can't find the cell2mask and mask2cell functions. Can you add them?

**Comment by motatoes** [comment]
Hey thanks for stopping by, yeah I'll do this as soon as I get a chance later today :)

**Comment by maybefreedom** [comment]
okay thank you !!

**Comment by motatoes** [comment]
@maybefreedom  can you please paste the exact MATLAB error that shows up when you attempt to run in a comment. I wanna know the line numbers where the imports are msising. Thanks

**Comment by maybefreedom** [comment]
Undefined variable "ria" or class "ria.util.mask2cell".


Error in Candidates/setFromBinaryImage (line 17)
            self.cellArray = mask2cell(binaryImage);

Error in detectFlemingCandidates (line 37)
    candidates.setFromBinaryImage( gaussImage >= (tau*5) );

In Candidates.m there are two functions:
function setFromBinaryImage(self, binaryImage, varargin)
            self.binaryImage = binaryImage;
            self.cellArray = ria.util.mask2cell(binaryImage);
        end
        
        function setFromCellArray(self, cellArray, imageSize, varargin)
            self.cellArray = cellArray;
            self.binaryImage = ria.util.cell2mask(cellArray, imageSize);
        end

where ria.util.cell2mask/mask2cell don't exist anywhere else.

**Comment by maybefreedom** [comment]
Have you found it? Also can you explain why you used mask2cell for the tresholding?

**Comment by motatoes** [comment]
Hey I've included the missing functions in 6e78274ac59fb7b37d9aa3a3e97825bc204eb6f0 

Please pull the code and then try running again to see if it works for you? Also we use a mask in order to extract only the field of view of the retina and exclude the black background. Since false positives can be detected around the borders of the retina field of view.

**Comment by maybefreedom** [comment]
yes it's working now! thank you
